---
- name: Configure Ubuntu servers
  hosts: ubuntu_servers
  vars:
    localhost_install: true
  become: true
  become_user: root
  gather_facts: true
  roles:
    - role: check_os
    - role: common
    - role: setup_hugepages
    - role: install_libbpf
    - role: install_dpdk
    - role: clone_repo
    - role: restart

