################################################################
#             1GB pages config                                 #
################################################################

- name: Check 1GB Hugepages Support in cpuinfo
  shell: cat /proc/cpuinfo | grep -q pdpe1gb && echo "FOUND" || echo "NOT FOUND"
  register: hugepages_1GB_check
  tags:
    - check_1GB_hugepages

- name: Check cpuinfo result
  debug:
    msg: selected 1GB hugepages but these are not supported by the system
  when: hugepages_1GB > 0 and hugepages_1GB_check.stdout != "FOUND"
  tags:
    - check_1GB_hugepages

- name: Modify existing 1GB Hugepages configuration if it exists
  replace:
    path: /etc/default/grub
    regexp: "{{ item.regex }}"
    replace: "{{ item.config }}"
  when:
    - hugepages_1GB > 0 and hugepages_1GB_check.stdout == "FOUND"
  loop:
    - {regex: '(GRUB_CMDLINE_LINUX=.*)([hugepagesz=][0-9][G|MB])(.*)', config: '\1=1G\3'}
    - {regex: '(GRUB_CMDLINE_LINUX=.*)([hugepages=][0-9]+)(.*)', config: '\1={{ hugepages_1GB }}\3'}
  tags:
    - config_1GB_hugepages

- name: Insert new 1GB configuration in grub if it doesn't exist
  replace:
    dest: /etc/default/grub
    regexp: "(GRUB_CMDLINE_LINUX=(?!.* default_hugepagesz)(?!.* hugepagesz)(?!.* hugepages)\"[^\"]*)(\".*)"
    replace: '\1 default_hugepagesz=1G hugepagesz=1G hugepages={{ hugepages_1GB }} transparent_hugepage=never iommu=pt intel_iommu=on\2'
  when:
    - hugepages_1GB > 0 and hugepages_1GB_check.stdout == "FOUND"
  tags:
    - config_1GB_hugepages

- name: update grub
  shell: update-grub
  when:
    - hugepages_1GB > 0 and hugepages_1GB_check.stdout == "FOUND"
  tags:
    - config_1GB_hugepages
